/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  EthereumConfig,
  EthereumConfigInterface,
} from "../../../../../@fhevm/solidity/config/ZamaConfig.sol/EthereumConfig";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
] as const;

const _bytecode =
  "0x60806040523461011d576060610013610122565b600091818380935282602082015282604082015201526060610033610122565b828152826020820152826040820152015260018060a01b03197fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6008181541690557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6018181541690557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6028181541690557fed8d60e34876f751cc8b014c560745351147d9de11b9347c854e881b128ea6038181541690557f5ea69329017273582817d320489fbd94f775580e90c092699ca6f3d12fdf7d00908154169055604051603a90816101588239f35b600080fd5b60405190608082016001600160401b0381118382101761014157604052565b634e487b7160e01b600052604160045260246000fdfe600080fdfea2646970667358221220c7cc83e7110edfd812259b7c97bf9fe3e38c70fcd74ce2127a10a8752947e0b564736f6c63430008180033";

type EthereumConfigConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumConfigConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumConfig__factory extends ContractFactory {
  constructor(...args: EthereumConfigConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EthereumConfig & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EthereumConfig__factory {
    return super.connect(runner) as EthereumConfig__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumConfigInterface {
    return new Interface(_abi) as EthereumConfigInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EthereumConfig {
    return new Contract(address, _abi, runner) as unknown as EthereumConfig;
  }
}
